name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing! Please read the contributing.md file, and if you already have, thanks!'
        pr-message: 'Hi! Thanks for contributing! If you have not already, please read the contributing.md file.'
